// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwiuLPLmlw0pyHq0YK0f7Kn4-XA4SYE84',
    appId: '1:76019636534:web:767bcb2d33d3cb5852bb97',
    messagingSenderId: '76019636534',
    projectId: 'powerplantlogsheet-8780a',
    authDomain: 'powerplantlogsheet-8780a.firebaseapp.com',
    storageBucket: 'powerplantlogsheet-8780a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcCiqCPSjzID0sWz39xxelcsHxJ8GWAUU',
    appId: '1:76019636534:android:eb26908260c4d4e152bb97',
    messagingSenderId: '76019636534',
    projectId: 'powerplantlogsheet-8780a',
    storageBucket: 'powerplantlogsheet-8780a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCjsc4W17cePSARihnPU65zHh6ZzImGJ4',
    appId: '1:76019636534:ios:d2cba12cf87bdb6b52bb97',
    messagingSenderId: '76019636534',
    projectId: 'powerplantlogsheet-8780a',
    storageBucket: 'powerplantlogsheet-8780a.firebasestorage.app',
    iosBundleId: 'com.example.flutterCoba3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCjsc4W17cePSARihnPU65zHh6ZzImGJ4',
    appId: '1:76019636534:ios:d2cba12cf87bdb6b52bb97',
    messagingSenderId: '76019636534',
    projectId: 'powerplantlogsheet-8780a',
    storageBucket: 'powerplantlogsheet-8780a.firebasestorage.app',
    iosBundleId: 'com.example.flutterCoba3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwiuLPLmlw0pyHq0YK0f7Kn4-XA4SYE84',
    appId: '1:76019636534:web:3324aa524717fbc052bb97',
    messagingSenderId: '76019636534',
    projectId: 'powerplantlogsheet-8780a',
    authDomain: 'powerplantlogsheet-8780a.firebaseapp.com',
    storageBucket: 'powerplantlogsheet-8780a.firebasestorage.app',
  );
}
